# Generated by Django 2.2.17 on 2020-12-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20201215_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('website', models.CharField(blank=True, max_length=80)),
                ('facebook', models.CharField(blank=True, max_length=80)),
                ('instagram', models.CharField(blank=True, max_length=80)),
                ('twitter', models.CharField(blank=True, max_length=80)),
                ('discord', models.CharField(blank=True, max_length=80)),
                ('github', models.CharField(blank=True, max_length=80)),
                ('linkedin', models.CharField(blank=True, max_length=80)),
                ('youtube', models.CharField(blank=True, max_length=80)),
                ('spotify', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
